fixtures:
  repositories:
    "augeas_core": "https://github.com/puppetlabs/puppetlabs-augeas_core.git"
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    provision: "https://github.com/puppetlabs/provision.git"
    puppet_agent:
      repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
      ref: v4.13.0
    package: "https://github.com/puppetlabs/puppetlabs-package.git"
    deploy_pe: "https://github.com/jarretlavallee/puppet-deploy_pe"
    sign_cert: "https://github.com/m0dular/sign_cert"
    ruby_task_helper: "https://git@github.com/puppetlabs/puppetlabs-ruby_task_helper"
    bootstrap: "https://github.com/puppetlabs/puppetlabs-bootstrap"
    puppet_conf: "https://github.com/puppetlabs/puppetlabs-puppet_conf"
  symlinks:
    "ntp": "#{source_dir}"
    "my_ntp": "#{source_dir}/spec/fixtures/my_ntp"
