---
.travis.yml:
  includes:
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4.0"
    bundler_args: --without system_tests
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0"
    bundler_args: --without system_tests
